In [1]:
import numpy as np
import pandas as pd

In [34]:
production_areas_data = pd.read_csv("../Data/Breakdown_of_main_electricity_generation_facilities_in_France,_excluding_solar_and_wind_power_plants_2026-02-25_09-08.csv", sep=";")
generation_data = pd.read_csv("../Data/Evolution_of_power_generation_in_France_2026-03-02_18-36.csv", delimiter=";")
countries = pd.read_csv("../Data/ALLCOUNTRIES.csv")

/var/folders/nc/h_k99bk14lv76j0fpvszb2f40000gn/T/ipykernel_9317/1854614690.py:3: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  countries = pd.read_csv("../Data/ALLCOUNTRIES.csv")

In [35]:
generation_data

         Date            Filière     Valeur (TWh)               Nature
0     1995-01            Nuclear           36,909  Données Consolidées
1     1995-02            Nuclear           30,157  Données Consolidées
2     1995-03            Nuclear           32,737  Données Consolidées
3     1995-04            Nuclear           29,125  Données Consolidées
4     1995-05            Nuclear           26,749  Données Consolidées
...       ...                ...              ...                  ...
2759  2025-10   Total generation  44,650769402949  Données Consolidées
2760  2025-11   Total generation  49,905099386246  Données Consolidées
2761  2025-12   Total generation  56,384121200713  Données Consolidées
2762  2026-01   Total generation  57,467545370334  Données Consolidées
2763  2026-02   Total generation      48,35762725  Données provisoires

[2764 rows x 4 columns]

In [36]:
production_areas_data

,Commune,Longitude,Latitude,Filière,Valeur (MW)
0,Saint-Vulbas,5.270397,45.822404,Nuclear,3580
1,Cruas,4.756096,44.656491,Nuclear,3660
2,Chooz,4.801001,50.089525,Nuclear,3000
3,Nogent-sur-Seine,3.499683,48.496487,Nuclear,2620
4,Belleville-sur-Loire,2.845587,47.501500,Nuclear,2620
...,...,...,...,...,...
139,Vitry-sur-Seine,2.394516,48.788118,Fossil-fired thermal,350
140,Gardanne,5.480112,43.452894,Renewable thermal and waste,150
141,Étagnac,0.783565,45.890606,Renewable thermal and waste,"55,25"
142,Biganos,-0.949164,44.660950,Renewable thermal and waste,"59,5"
143,Ivry-sur-Seine,2.387710,48.812288,Renewable thermal and waste,55

In [37]:
countries = countries.dropna()
countries.columns = countries.iloc[0]
countries = countries.iloc[1:]
countries

7,Country,Time,Balance,Product,Value,Unit
8,Australia,November 2025,Net Electricity Production,Electricity,21355.0142,GWh
9,Australia,November 2025,Net Electricity Production,Hydro,965.5352,GWh
10,Australia,November 2025,Net Electricity Production,Total Combustible Fuels,11343.0954,GWh
11,Australia,November 2025,Net Electricity Production,"Coal, Peat and Manufactured Gases",8266.798,GWh
12,Australia,November 2025,Net Electricity Production,Oil and Petroleum Products,263.3526,GWh
...,...,...,...,...,...,...
157377,IEA Total,January 2010,Total Exports,Electricity,32372.583,GWh
157378,IEA Total,January 2010,Used for pumped storage,Electricity,6869.253,GWh
157379,IEA Total,January 2010,Distribution Losses,Electricity,62000.733,GWh
157380,IEA Total,January 2010,Final Consumption (Calculated),Electricity,877213.615,GWh
157381,IEA Total,January 2010,Net Electricity Production,Wind,21659.612,GWh

In [41]:
countries.columns

Index(['Country', 'Time', 'Balance', 'Product', 'Value', 'Unit'], dtype='object', name=7)

In [42]:
countries["Time"].unique()

array(['November 2025', 'October 2025', 'September 2025', 'August 2025',
       'July 2025', 'June 2025', 'May 2025', 'April 2025', 'March 2025',
       'February 2025', 'January 2025', 'December 2024', 'November 2024',
       'October 2024', 'September 2024', 'August 2024', 'July 2024',
       'June 2024', 'May 2024', 'April 2024', 'March 2024',
       'February 2024', 'January 2024', 'December 2023', 'November 2023',
       'October 2023', 'September 2023', 'August 2023', 'July 2023',
       'June 2023', 'May 2023', 'April 2023', 'March 2023',
       'February 2023', 'January 2023', 'December 2022', 'November 2022',
       'October 2022', 'September 2022', 'August 2022', 'July 2022',
       'June 2022', 'May 2022', 'April 2022', 'March 2022',
       'February 2022', 'January 2022', 'December 2021', 'November 2021',
       'October 2021', 'September 2021', 'August 2021', 'July 2021',
       'June 2021', 'May 2021', 'April 2021', 'March 2021',
       'February 2021', 'January 2021', 'December 2020', 'November 2020',
       'October 2020', 'September 2020', 'August 2020', 'July 2020',
       'June 2020', 'May 2020', 'April 2020', 'March 2020',
       'February 2020', 'January 2020', 'December 2019', 'November 2019',
       'October 2019', 'September 2019', 'August 2019', 'July 2019',
       'June 2019', 'May 2019', 'April 2019', 'March 2019',
       'February 2019', 'January 2019', 'December 2018', 'November 2018',
       'October 2018', 'September 2018', 'August 2018', 'July 2018',
       'June 2018', 'May 2018', 'April 2018', 'March 2018',
       'February 2018', 'January 2018', 'December 2017', 'November 2017',
       'October 2017', 'September 2017', 'August 2017', 'July 2017',
       'June 2017', 'May 2017', 'April 2017', 'March 2017',
       'February 2017', 'January 2017', 'December 2016', 'November 2016',
       'October 2016', 'September 2016', 'August 2016', 'July 2016',
       'June 2016', 'May 2016', 'April 2016', 'March 2016',
       'February 2016', 'January 2016', 'December 2015', 'November 2015',
       'October 2015', 'September 2015', 'August 2015', 'July 2015',
       'June 2015', 'May 2015', 'April 2015', 'March 2015',
       'February 2015', 'January 2015', 'December 2014', 'November 2014',
       'October 2014', 'September 2014', 'August 2014', 'July 2014',
       'June 2014', 'May 2014', 'April 2014', 'March 2014',
       'February 2014', 'January 2014', 'December 2013', 'November 2013',
       'October 2013', 'September 2013', 'August 2013', 'July 2013',
       'June 2013', 'May 2013', 'April 2013', 'March 2013',
       'February 2013', 'January 2013', 'December 2012', 'November 2012',
       'October 2012', 'September 2012', 'August 2012', 'July 2012',
       'June 2012', 'May 2012', 'April 2012', 'March 2012',
       'February 2012', 'January 2012', 'December 2011', 'November 2011',
       'October 2011', 'September 2011', 'August 2011', 'July 2011',
       'June 2011', 'May 2011', 'April 2011', 'March 2011',
       'February 2011', 'January 2011', 'December 2010', 'November 2010',
       'October 2010', 'September 2010', 'August 2010', 'July 2010',
       'June 2010', 'May 2010', 'April 2010', 'March 2010',
       'February 2010', 'January 2010'], dtype=object)